default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: papermind_development

test:
  <<: *default
  database: papermind_test
